-- AlterTable
ALTER TABLE `Formaguadrenaje` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formalumbrado` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formanalisisestrategico` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formaseopublico` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formconservacion` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formconstruccion` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formdif` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Forminnovacion` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Forminspeccionvig` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formmejoramientourbano` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formpcivil` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formrecaudadora` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formsalud` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formseguridadpublica` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formsindicatura` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `Formtianguis` ADD COLUMN `creadoEn` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
